[hex]
bg = "#101010"
bg_alt = "#363636"
fg = "#e0e0e0"
border = "#999999"
accent = "#7CA6A6"
color0 = "#121212"
color1 = "#d66c6c"
color2 = "#7ad89a"
color3 = "#ffb07c"
color4 = "#84a7d8"
color5 = "#b586c6"
color6 = "#80c9b2"
color7 = "#d6d6d6"
color8 = "#8c8c8c"
color9 = "#f08a85"
color10 = "#a4e0b3"
color11 = "#ffc290"
color12 = "#a8c9f3"
color13 = "#d9b3e1"
color14 = "#a6dbcc"
color15 = "#f5f5f5"
