[rgb]
bg = "16, 16, 16"
bg_alt = "54, 54, 54"
fg = "224, 224, 224"
border = "153, 153, 153"
accent = "124, 166, 166"
color0 = "18, 18, 18"
color1 = "214, 108, 108"
color2 = "122, 216, 154"
color3 = "255, 176, 124"
color4 = "132, 167, 216"
color5 = "181, 134, 198"
color6 = "128, 201, 178"
color7 = "214, 214, 214"
color8 = "140, 140, 140"
color9 = "240, 138, 133"
color10 = "164, 224, 179"
color11 = "255, 194, 144"
color12 = "168, 201, 243"
color13 = "217, 179, 225"
color14 = "166, 219, 204"
color15 = "245, 245, 245"
